title: Cheng Song's Homepage
page-top-title: Cheng Song
top-section-bg-text: Welcome to my homepage!
home-subtitle: Cheng Song&ensp;|&ensp;宋澄
copyright-text: '&copy; Cheng Song 2025. All Rights Reserved.'
